default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kid-friendly_development

test:
  <<: *default
  database: kid-friendly_test

production:
  <<: *default
  database: kid-friendly_production
  username: kid-friendly
  password: <%= ENV['KID-FRIENDLY_DATABASE_PASSWORD'] %>

